# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=arm
HWLIB=../libhw32/libqemuhw32.a
CONFIG_SOFTMMU=yes
TARGET_XML_FILES= /root/mini2440_qemu/qemu/gdb-xml/arm-core.xml /root/mini2440_qemu/qemu/gdb-xml/arm-vfp.xml /root/mini2440_qemu/qemu/gdb-xml/arm-vfp3.xml /root/mini2440_qemu/qemu/gdb-xml/arm-neon.xml
CONFIG_SOFTFLOAT=yes
