/* Automatically generated by configure - do not modify */
#define CONFIG_QEMU_SHAREDIR "/usr/local/share/qemu"
#define HOST_I386 1
#define HOST_LONG_BITS 32
#define HAVE_BYTESWAP_H 1
#define CONFIG_SLIRP 1
#define CONFIG_AC97 1
#define CONFIG_ES1370 1
#define CONFIG_SB16 1
#define AUDIO_DRIVERS \
    &oss_audio_driver, \

#define HAVE_FNMATCH_H 1
#define QEMU_VERSION "0.10.50"
#define QEMU_PKGVERSION ""
#define CONFIG_SDL 1
#define CONFIG_CURSES 1
#define CONFIG_ATFILE 1
#define CONFIG_INOTIFY 1
#define CONFIG_AIO 1
#define HAVE_IOVEC 1
#define HAVE_PREADV 1
#define CONFIG_UNAME_RELEASE ""
